"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
import time
from pathlib import Path
from urllib.parse import urlparse

from dotenv import load_dotenv

# Bare apex for this site often does not load in the browser; outbound links (email, Stripe)
# should use https://www.<apex>. Additional domains: set SITE_USE_WWW_FOR_HOST=comma-separated.
_SITE_WWW_APEX_DEFAULTS = frozenset({"setfreeinchristmission.org"})


def _normalize_site_base_url(raw: str) -> str:
    """
    Strip trailing slash from the public site URL.

    For listed apex hostnames (defaults + SITE_USE_WWW_FOR_HOST), rewrite
    https://apex/... → https://www.apex/... so emails and Stripe use the host that actually responds.
    """
    url = (raw or "").strip().rstrip("/")
    if not url:
        return "http://127.0.0.1:8000"
    apex_hosts: set[str] = set(_SITE_WWW_APEX_DEFAULTS)
    apex_hosts.update(
        h.strip().lower()
        for h in os.getenv("SITE_USE_WWW_FOR_HOST", "").split(",")
        if h.strip()
    )
    if "://" not in url:
        url = "https://" + url.lstrip("/")
    parsed = urlparse(url)
    if not parsed.hostname:
        return url
    host = parsed.hostname.lower()
    if host in apex_hosts and not host.startswith("www."):
        netloc = f"www.{host}"
        if parsed.port:
            netloc = f"{netloc}:{parsed.port}"
        return parsed._replace(netloc=netloc).geturl().rstrip("/")
    return url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY", "django-insecure-change-this-key-for-production"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "*").split(",")]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "intensive.apps.IntensiveConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'intensive.context_processors.static_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- Upload size (Django) vs "413 Request Entity Too Large" (web server) ---------------
#
# A 413 error means the REVERSE PROXY (Nginx, OpenResty, Cloudflare, or your host) rejected
# the request body BEFORE it reached Django. Changing the values below does NOT fix 413.
#
# Fix 413 where your site is actually served:
#   • Nginx / OpenResty: set client_max_body_size (e.g. 500m) in http { }, server { }, or
#     location { }, then reload:  nginx -s reload
#   • PythonAnywhere: limits are set by the platform; check their docs / support / plan.
#   • Cloudflare: free/proxy tiers limit upload size; use a direct origin URL or higher tier,
#     or host large files elsewhere (YouTube/Vimeo/S3) and use a link in the admin form.
#
# The settings below only apply AFTER the request is allowed through to Django: they control
# how much of the request/file is held in memory vs spooled to disk (still keep these set).
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # non-file parts of POST; 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # buffer before streaming to temp file; 10 MB

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@freedomintensive.local")

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

SITE_BASE_URL = _normalize_site_base_url(os.getenv("SITE_BASE_URL", "http://127.0.0.1:8000"))
ADMIN_NOTIFICATION_EMAIL = os.getenv("ADMIN_NOTIFICATION_EMAIL", "")
STATIC_VERSION = os.getenv("STATIC_VERSION", str(int(time.time())))

LOGIN_URL = "/dashboard/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

# Sessions: log out after this many minutes of *inactivity* (no page loads / requests).
# SESSION_SAVE_EVERY_REQUEST extends the deadline on each request, so only idle time counts.
_idle_minutes = int(os.getenv("SESSION_IDLE_TIMEOUT_MINUTES", "15"))
SESSION_COOKIE_AGE = max(60, _idle_minutes * 60)  # at least 1 minute; value is in seconds
SESSION_SAVE_EVERY_REQUEST = True

# On HTTPS (production), set SESSION_COOKIE_SECURE=True so the cookie is not sent over HTTP.
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "False").lower() == "true"
SESSION_COOKIE_HTTPONLY = True
