# Generated by Django 6.0.3 on 2026-03-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensive', '0003_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(default='Lagos, Nigeria', max_length=180),
        ),
    ]
