# Generated by Django 6.0.3 on 2026-03-04 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensive', '0004_session_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.CharField(default='Dallas, TX, USA', max_length=180),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='venue_address',
            field=models.CharField(default='Freedom Revival Center, 1200 Main St, Dallas, TX 75202, USA', max_length=255),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('role_title', models.CharField(max_length=180)),
                ('role_subtitle', models.CharField(blank=True, max_length=180)),
                ('country_code', models.CharField(blank=True, help_text='ISO alpha-2 code, e.g. us, gb', max_length=2)),
                ('country_label', models.CharField(blank=True, max_length=80)),
                ('photo_url', models.URLField(blank=True, help_text='Use an image URL for speaker headshot.')),
                ('read_more_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sessions', models.ManyToManyField(blank=True, related_name='speakers', to='intensive.session')),
            ],
            options={
                'ordering': ['display_order', 'full_name'],
            },
        ),
    ]
