# Generated by Django 6.0.3 on 2026-03-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensive', '0006_speaker_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
