# Generated by Django 6.0.3 on 2026-03-05 06:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensive', '0008_rename_registration_state_to_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CHECKOUT_CREATED', 'Checkout Created'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_CANCELED', 'Payment Canceled'), ('PAYMENT_ERROR', 'Payment Error')], max_length=32)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELED', 'Canceled')], max_length=16)),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe')], default='STRIPE', max_length=16)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('payment_ref', models.CharField(blank=True, max_length=200)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='intensive.registration')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='intensive.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
