# Generated by Django 6.0.3 on 2026-03-05 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensive', '0009_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='donation_url',
            field=models.URLField(blank=True, help_text='Public donation page URL (for example Donor Elf).'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='DONOR_ELF', max_length=32)),
                ('provider_ref', models.CharField(blank=True, max_length=200)),
                ('donor_name', models.CharField(blank=True, max_length=160)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.PositiveIntegerField(default=0, help_text='Stored in the smallest currency unit.')),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='intensive_d_status_62fa0f_idx'), models.Index(fields=['provider_ref'], name='intensive_d_provide_7c84df_idx'), models.Index(fields=['donor_email'], name='intensive_d_donor_e_1668f0_idx')],
            },
        ),
    ]
