# Generated by Django 6.0.3 on 2026-03-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensive', '0010_sitesetting_donation_url_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='frequency',
            field=models.CharField(choices=[('ONE_TIME', 'One-time'), ('MONTHLY', 'Monthly')], default='ONE_TIME', max_length=16),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='donation',
            name='provider',
            field=models.CharField(default='STRIPE', max_length=32),
        ),
    ]
