# Generated by Django 6.0.3 on 2026-03-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensive', '0011_donation_donor_message_donation_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='role_subtitle',
            field=models.TextField(blank=True),
        ),
    ]
