# Generated by Django 6.0.3 on 2026-03-06 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensive', '0012_alter_speaker_role_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='Discount in the smallest currency unit.'),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='student_discount_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='registration',
            name='student_id',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='student_discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Student discount percent for registration (0-95).'),
        ),
        migrations.CreateModel(
            name='StudentDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_codes_used', to='intensive.registration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_id', 'email'], name='intensive_s_student_d8cd1d_idx'), models.Index(fields=['code'], name='intensive_s_code_e62132_idx'), models.Index(fields=['is_used'], name='intensive_s_is_used_701eb8_idx')],
            },
        ),
    ]
