# Generated by Django 6.0.3 on 2026-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensive', '0013_registration_discount_amount_registration_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
