# Generated by Django 6.0.3 on 2026-03-30 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensive', '0019_participant_portal_portalvideo_registration_portal_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='freeregistrationcode',
            new_name='intensive_f_is_used_b348f9_idx',
            old_name='intensive_fr_is_used_9f5e2a_idx',
        ),
        migrations.AlterField(
            model_name='freeregistrationcode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('FREE_CODE', 'Free Registration Code')], default='STRIPE', max_length=16),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_provider',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('FREE_CODE', 'Free Registration Code')], default='STRIPE', max_length=16),
        ),
        migrations.AlterField(
            model_name='registrationmaterial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
