# Generated by Django 6.0.3 on 2026-07-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intensive', '0028_donation_donor_tax_fields'),
        ('intensive', '0028_registration_requested_payment_method'),
    ]

    operations = [
    ]
